compatibility_date = "2022-05-20"
kv_namespaces = [
  {binding = "POOLS", id = "8d7d1a9f29ff453db4749a54022a3c51", preview_id = "8d7d1a9f29ff453db4749a54022a3c51"},
]
r2_buckets = [
  { binding = "SUBGRAPH_POOLS", bucket_name = "subgraph-pools-dev" }
]
main = "src/index.ts"
name = "routing-dev"
node_compat = true
[triggers]
crons = ["0 0 * * *"]

[env.production]
kv_namespaces = [
  {binding = "POOLS", id = "8d7d1a9f29ff453db4749a54022a3c51"},
]
r2_buckets = [
  { binding = "SUBGRAPH_POOLS", bucket_name = "subgraph-pools", preview_bucket_name = "subgraph-pools-dev" }
]
name = "routing"
[env.production.triggers]
crons = ["*/30 * * * *"]

# The necessary secrets are:
# - ETH_NODE
# - GOERLI_NODE
# - BSC_NODE
# - BSC_TESTNET_NODE
# - NODE_REAL_SUBGRAPH_API_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
