[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
publish = ".next"
[context.deploy-preview]
ignore = "if [[ $HEAD == *feature/* ]]; then exit 1; else exit 0; fi"

[[headers]]
for = "/_next/static/*"
[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"
[headers.values]
cache-control = "public, no-transform, immutable, max-age=604800"

[[redirects]]
  from = "/"
  to = "/cu/"
  status = 302
  force = true
  conditions = {Country=["BY","MM","CI","CU","CD","IR","IQ","LR","KP","SD","SY","ZW"]}

[[redirects]]
  from = "/swap"
  to = "/cu/swap/"
  status = 302
  force = true
  conditions = {Country=["BY","MM","CI","CU","CD","IR","IQ","LR","KP","SD","SY","ZW"]}

[[redirects]]
  from = "/liquidity"
  to = "/cu/liquidity/"
  status = 302
  force = true
  conditions = {Country=["BY","MM","CI","CU","CD","IR","IQ","LR","KP","SD","SY","ZW"]}

[[redirects]]
  from = "/farms"
  to = "/cu/farms/"
  status = 302
  force = true
  conditions = {Country=["BY","MM","CI","CU","CD","IR","IQ","LR","KP","SD","SY","ZW"]}

[[redirects]]
  from = "/pools"
  to = "/cu/pools/"
  status = 302
  force = true
  conditions = {Country=["BY","MM","CI","CU","CD","IR","IQ","LR","KP","SD","SY","ZW"]}

[[redirects]]
  from = "/ifo"
  to = "/cu/ifo/"
  status = 302
  force = true
  conditions = {Country=["BY","MM","CI","CU","CD","IR","IQ","LR","KP","SD","SY","ZW"]}

[[redirects]]
  from = "/competition"
  to = "/cu/competition/"
  status = 302
  force = true
  conditions = {Country=["BY","MM","CI","CU","CD","IR","IQ","LR","KP","SD","SY","ZW"]}

[[redirects]]
  from = "/prediction"
  to = "/cu/prediction/"
  status = 302
  force = true
  conditions = {Country=["BY","MM","CI","CU","CD","IR","IQ","LR","KP","SD","SY","ZW"]}

[[redirects]]
  from = "/lottery"
  to = "/cu/lottery/"
  status = 302
  force = true
  conditions = {Country=["BY","MM","CI","CU","CD","IR","IQ","LR","KP","SD","SY","ZW"]}

[[redirects]]
  from = "/nfts"
  to = "/cu/nfts/"
  status = 302
  force = true
  conditions = {Country=["BY","MM","CI","CU","CD","IR","IQ","LR","KP","SD","SY","ZW"]}

[[redirects]]
  from = "/voting"
  to = "/cu/voting/"
  status = 302
  force = true
  conditions = {Country=["BY","MM","CI","CU","CD","IR","IQ","LR","KP","SD","SY","ZW"]}

[[redirects]]
  from = "/info"
  to = "/cu/info/"
  status = 302
  force = true
  conditions = {Country=["BY","MM","CI","CU","CD","IR","IQ","LR","KP","SD","SY","ZW"]}
