on:
  workflow_dispatch:
    inputs:
      api:
        description: 'API'
        required: true
        type: choice
        options:
          - routing
      environment:
        description: 'Choose an environment to deploy to: <dev|production>'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      HAVE_CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN != '' }}
    name: Publish API
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'apis/${{ github.event.inputs.api }}'
          command: publish --env ${{ github.event.inputs.environment }}
