name: Integration Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cypress install
        run: yarn install --frozen-lockfile
      - run: yarn cypress install
      - run: yarn build
        env:
          NEXT_PUBLIC_SF_HEADER: ${{ secrets.SF_HEADER }}
      - run: yarn integration-test
