name: Integration Tests

on:
  # Note: pull_request_target instead of pull_request to allow workflow access to secrets
  pull_request:
    branches:
      - develop

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org
      - run: yarn install --frozen-lockfile
      - run: yarn cypress install
      - name: Wait for Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.2
        id: netlify
        with:
          site_name: 'pancakeswap-dev'
          max_timeout: 300
      - run: echo ${{ steps.netlify.outputs.url }}
      - run: yarn integration-test
        env:
          CYPRESS_BASE_URL: ${{ steps.netlify.outputs.url }}
