name: Sync base branch from public repo

on:
  workflow_dispatch:
  schedule:
    # 23:15 UTC
    # GitHub Actions might be delayed if time is at exact hour
    - cron: "30 4 * * *"

jobs:
  syncPublicBase:
    runs-on: ubuntu-latest
    if: github.repository == 'pancakeswap/frontend-private'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: refs/heads/v3

      - name: Reset the current branch with upstream changes
        run: |
          git remote add upstream https://github.com/pancakeswap/pancake-frontend.git
          git fetch upstream develop:upstream-develop
          git reset --hard upstream-develop

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          author: PancakeSwap Bot <pancakeswap-bot@protonmail.com>
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore: Sync upstream develop"
          body: |
            - Sync latest upstream develop

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          delete-branch: true
          labels: automerge
          branch: upstream-develop
